services:
  backend_test:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: test
    environment:
      - PYTHONPATH=/app  # Add /app to Python's module search path
    networks:
      - app_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: service
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./instagram.db  # Or your actual database URL

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
