version: "3.8"

services:
  backend:
    build:
      context: ./
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - backend_data:/app
    environment:
      - DATABASE_URL=sqlite:///./instagram.db  # Or your actual database URL
    depends_on:
      []
    networks:
      - app_network

  frontend:
    build:
      context: ./
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - frontend_data:/app
    depends_on:
      - backend
    networks:
      - app_network

volumes:
  backend_data:
  frontend_data:

networks:
  app_network:
    driver: bridge
