name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build all containers
      run: docker compose build
      
    - name: Run backend tests
      run: docker compose run --rm backend_test
      
    - name: Start all services
      run: docker compose up -d
      
    - name: Wait for services to be ready
      run: |
        # Wait for backend to be ready
        timeout 30 bash -c 'until curl -f http://localhost:8000/; do sleep 1; done'
        
    - name: Run integration test
      run: |
        # Test that the API is responding
        curl -f http://localhost:8000/ | grep "Welcome to the Instagram Clone"
        
    - name: Stop all services
      run: docker compose down
